#ifndef HTML_FILES_H
#define HTML_FILES_H

// control.html
// control.html (corrected full version)
const char control_html[] =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"  <meta charset=\"UTF-8\" />\n"
"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"  <title>ENERGIS PDU - Control</title>\n"
"  <style>\n"
"    * {margin:0;padding:0;box-sizing:border-box;}\n"
"    body { background-color: #1a1d23; color: #e4e4e4; font-family: sans-serif; }\n"
"    .topbar { width: 100%; height: 50px; background-color: #242731; display: flex; padding: 10px; justify-content: space-between; align-items: center; }\n"
"    .container { display: flex; width: 100%; height: calc(100vh - 50px); }\n"
"    .sidebar { background-color: #1f222a; padding: 20px; width: 200px; }\n"
"    .sidebar ul { list-style: none; padding: 0; }\n"
"    .sidebar ul li { padding: 8px 0; }\n"
"    .main-content { padding: 20px; flex-grow: 1; }\n"
"    table { width: 100%; border-collapse: collapse; }\n"
"    th, td { padding: 8px; border-bottom: 1px solid #3f4450; }\n"
"    .switch { position: relative; display: inline-block; width: 50px; height: 24px; }\n"
"    .switch input { opacity: 0; width: 0; height: 0; }\n"
"    .slider { position: absolute; cursor: pointer; background-color: #ccc; top: 0; left: 0; right: 0; bottom: 0; transition: .4s; border-radius: 24px; }\n"
"    .slider:before { position: absolute; content: ''; height: 18px; width: 18px; left: 4px; bottom: 3px; background-color: white; transition: .4s; border-radius: 50%; }\n"
"    input:checked + .slider { background-color: #3fa7ff; }\n"
"    input:checked + .slider:before { transform: translateX(23px); }\n"
"  </style>\n"
"  <script>\n"
"    function updateStatus() {\n"
"      fetch('/api/status').then(response => response.json()).then(data => {\n"
"        for (let i = 1; i <= 8; i++) {\n"
"          document.getElementById('voltage-' + i).innerText = data.channels[i-1].voltage + ' V';\n"
"          document.getElementById('current-' + i).innerText = data.channels[i-1].current + ' A';\n"
"          document.getElementById('uptime-' + i).innerText = data.channels[i-1].uptime + ' min';\n"
"          document.getElementById('power-' + i).innerText = data.channels[i-1].power + ' W';\n"
"        }\n"
"        document.getElementById('internal-temperature').innerText = data.internalTemperature + ' °C';\n"
"        document.getElementById('system-status').innerText = data.systemStatus;\n"
"      });\n"
"    });\n"
"    setInterval(updateStatus, 1000);\n"
"    function toggleChannel(channel) {\n"
"      fetch('/api/toggle/' + channel, {method: 'POST'}).then(response => response.json()).then(result => {\n"
"        updateStatus();\n"
"      });\n"
"    }\n"
"    document.addEventListener('DOMContentLoaded', updateStatus);\n"
"  </script>\n"
"</head>\n"
"<body>\n"
"  <div class=\"topbar\">\n"
"    <h1>ENERGIS Managed PDU</h1>\n"
"  </div>\n"
"  <div class=\"container\">\n"
"    <div class=\"sidebar\">\n"
"      <ul>\n"
"        <li><a href=\"control.html\">Control</a></li>\n"
"        <li><a href=\"user_manual.html\">User Manual</a></li>\n"
"        <li><a href=\"programming_manual.html\">Programming Manual</a></li>\n"
"      </ul>\n"
"    </div>\n"
"    <div class=\"main-content\">\n"
"      <h2>Status</h2>\n"
"      <table>\n"
"        <tr><th>Ch.</th><th>Voltage</th><th>Current</th><th>Uptime</th><th>Power</th><th>Switch</th></tr>\n"
"        <tr><td>1</td><td id=\"voltage-1\">--</td><td id=\"current-1\">--</td><td id=\"uptime-1\">--</td><td id=\"power-1\">--</td><td><label class=\"switch\"><input type=\"checkbox\" onclick=\"toggleChannel(1)\"><span class=\"slider\"></span></label></td></tr>\n"
"        <!-- Repeat for channels 2-8 similarly -->\n"
"      </table>\n"
"      <p>Internal Temperature: <span id=\"internal-temperature\">--</span></p>\n"
"      <p>System Status: <span id=\"system-status\">--</span></p>\n"
"    </div>\n"
"  </div>\n"
"</body>\n"
"</html>\n";


// settings.html
const char settings_html[] =
"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"  <meta charset=\"UTF-8\" />\n"
"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"  <title>ENERGIS PDU - Settings</title>\n"
"  <style>\n"
"    * { margin: 0; padding: 0; box-sizing: border-box; font-family: sans-serif; }\n"
"    body { background-color: #1a1d23; color: #e4e4e4; }\n"
"    a { text-decoration: none; color: #aaa; } a:hover { color: #fff; }\n"
"    .topbar { width: 100%; height: 50px; background-color: #242731; display: flex; align-items: center; padding: 0 20px; }\n"
"    .topbar h1 { font-size: 1.2rem; color: #fff; }\n"
"    .container { display: flex; width: 100%; height: calc(100vh - 50px); }\n"
"    .sidebar { width: 220px; background-color: #2e323c; padding: 20px 0; }\n"
"    .sidebar ul { list-style: none; }\n"
"    .sidebar ul li { padding: 10px 20px; }\n"
"    .sidebar ul li:hover { background-color: #3b404d; }\n"
"    .main-content { flex: 1; padding: 20px; overflow-y: auto; }\n"
"    h2 { margin-bottom: 0.5rem; }\n"
"    p { margin: 0.5rem 0; }\n"
"    .status { margin-top: 1rem; background-color: #2e323c; padding: 10px; border-radius: 4px; }\n"
"    input, select, textarea { padding: 8px; margin-top: 4px; margin-bottom: 8px; border: none; border-radius: 4px; }\n"
"    input[type=text] { width: 200px; }\n"
"    .btn { background-color: #3fa7ff; border: none; padding: 10px 16px; color: #fff; cursor: pointer; border-radius: 4px; font-size: 0.9rem; }\n"
"    .btn:hover { background-color: #1f8ae3; }\n"
"    table { width: 100%; border-collapse: collapse; margin-top: 1rem; }\n"
"    th, td { text-align: left; padding: 0.75rem; border-bottom: 1px solid #3f4450; }\n"
"    th { background-color: #2e323c; }\n"
"  </style>\n"
"</head>\n"
"<body>\n"
"  <div class=\"topbar\"><h1>ENERGIS PDU</h1></div>\n"
"  <div class=\"container\">\n"
"    <div class=\"sidebar\">\n"
"      <ul>\n"
"        <li><a href=\"control.html\">Control</a></li>\n"
"        <li><a href=\"settings.html\">Settings</a></li>\n"
"        <li><a href=\"help.html\">Help</a></li>\n"
"        <li><a href=\"user_manual.html\">User Manual</a></li>\n"
"        <li><a href=\"programming_manual.html\">Programming Manual</a></li>\n"
"      </ul>\n"
"    </div>\n"
"    <div class=\"main-content\">\n"
"      <h2>Settings</h2>\n"
"      <form method=\"post\" action=\"/settings\">\n"
"        <h3>Network Settings</h3>\n"
"        <hr color=\"#333333\">\n"
"        <p>IP Address: <input type=\"text\" name=\"ip\" value=\"192.168.1.100\"><br>\n"
"           Default Gateway: <input type=\"text\" name=\"gateway\" value=\"192.168.1.1\"><br>\n"
"           Subnet Mask: <input type=\"text\" name=\"subnet\" value=\"255.255.255.0\"></p>\n"
"        <h3>Device Settings</h3>\n"
"        <hr color=\"#333333\">\n"
"        <p>Device Name: <input type=\"text\" name=\"device_name\" value=\"ENERGIS\"><br>\n"
"           Device Location: <input type=\"text\" name=\"location\" value=\"Server Room\"></p>\n"
"        <h3>Time Settings</h3>\n"
"        <hr color=\"#333333\">\n"
"        <p>Timezone: <input type=\"text\" name=\"timezone\" value=\"UTC\"><br>\n"
"           Time (HH:MM:SS): <input type=\"text\" name=\"time\" value=\"12:00:00\"></p>\n"
"        <h3>Security Settings</h3>\n"
"        <hr color=\"#333333\">\n"
"        <p>Auto Logout (minutes, 0 = off): <input type=\"text\" name=\"autologout\" value=\"5\"></p>\n"
"        <h3>Temperature Unit</h3>\n"
"        <hr color=\"#333333\">\n"
"        <p><input type=\"radio\" name=\"temp_unit\" value=\"celsius\" checked> Celsius<br>\n"
"           <input type=\"radio\" name=\"temp_unit\" value=\"fahrenheit\"> Fahrenheit<br>\n"
"           <input type=\"radio\" name=\"temp_unit\" value=\"kelvin\"> Kelvin</p>\n"
"        <br><input type=\"submit\" value=\"Save Settings\" class=\"btn\">\n"
"      </form>\n"
"      <h3>Manuals</h3>\n"
"      <hr color=\"#333333\">\n"
"      <p><a href=\"user_manual.html\">User Manual</a><br>\n"
"         <a href=\"programming_manual.html\">Programming &amp; Interfacing Manual</a></p>\n"
"    </div>\n"
"  </div>\n"
"</body>\n"
"</html>\n";

// help.html
const char help_html[] =
"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"  <meta charset=\"UTF-8\" />\n"
"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"  <title>ENERGIS PDU - Help</title>\n"
"  <style>\n"
"    * { margin: 0; padding: 0; box-sizing: border-box; font-family: sans-serif; }\n"
"    body { background-color: #1a1d23; color: #e4e4e4; }\n"
"    a { text-decoration: none; color: #aaa; } a:hover { color: #fff; }\n"
"    .topbar { width: 100%; height: 50px; background-color: #242731; display: flex; align-items: center; padding: 0 20px; }\n"
"    .topbar h1 { font-size: 1.2rem; color: #fff; }\n"
"    .container { display: flex; width: 100%; height: calc(100vh - 50px); }\n"
"    .sidebar { width: 220px; background-color: #2e323c; padding: 20px 0; }\n"
"    .sidebar ul { list-style: none; }\n"
"    .sidebar ul li { padding: 10px 20px; }\n"
"    .sidebar ul li:hover { background-color: #3b404d; }\n"
"    .main-content { flex: 1; padding: 20px; overflow-y: auto; }\n"
"    h2 { margin-bottom: 0.5rem; }\n"
"    p { margin: 0.5rem 0; }\n"
"    ul { margin-left: 20px; }\n"
"  </style>\n"
"</head>\n"
"<body>\n"
"  <div class=\"topbar\"><h1>ENERGIS PDU</h1></div>\n"
"  <div class=\"container\">\n"
"    <div class=\"sidebar\">\n"
"      <ul>\n"
"        <li><a href=\"control.html\">Control</a></li>\n"
"        <li><a href=\"settings.html\">Settings</a></li>\n"
"        <li><a href=\"help.html\">Help</a></li>\n"
"        <li><a href=\"user_manual.html\">User Manual</a></li>\n"
"        <li><a href=\"programming_manual.html\">Programming Manual</a></li>\n"
"      </ul>\n"
"    </div>\n"
"    <div class=\"main-content\">\n"
"      <h2>Help</h2>\n"
"      <p>Welcome to the ENERGIS PDU Help page.</p>\n"
"      <p>For detailed instructions, see:</p>\n"
"      <ul>\n"
"        <li><a href=\"user_manual.html\">User Manual</a></li>\n"
"        <li><a href=\"programming_manual.html\">Programming &amp; Interfacing Manual</a></li>\n"
"      </ul>\n"
"      <p>Use the Control page to toggle channels and monitor power. Use the Settings page to configure network, device, and time.</p>\n"
"    </div>\n"
"  </div>\n"
"</body>\n"
"</html>\n";

// user_manual.html
const char user_manual_html[] =
"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"  <meta charset=\"UTF-8\" />\n"
"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"  <title>ENERGIS PDU - User Manual</title>\n"
"  <style>\n"
"    * { margin: 0; padding: 0; box-sizing: border-box; font-family: sans-serif; }\n"
"    body { background-color: #1a1d23; color: #e4e4e4; }\n"
"    a { text-decoration: none; color: #aaa; } a:hover { color: #fff; }\n"
"    .topbar { width: 100%; height: 50px; background-color: #242731; display: flex; align-items: center; padding: 0 20px; }\n"
"    .topbar h1 { font-size: 1.2rem; color: #fff; }\n"
"    .container { display: flex; width: 100%; height: calc(100vh - 50px); }\n"
"    .sidebar { width: 220px; background-color: #2e323c; padding: 20px 0; }\n"
"    .sidebar ul { list-style: none; }\n"
"    .sidebar ul li { padding: 10px 20px; }\n"
"    .sidebar ul li:hover { background-color: #3b404d; }\n"
"    .main-content { flex: 1; padding: 20px; overflow-y: auto; }\n"
"    h2 { margin-bottom: 0.5rem; }\n"
"    p { margin: 0.5rem 0; }\n"
"    ul { margin-left: 20px; }\n"
"  </style>\n"
"</head>\n"
"<body>\n"
"  <div class=\"topbar\"><h1>ENERGIS PDU</h1></div>\n"
"  <div class=\"container\">\n"
"    <div class=\"sidebar\">\n"
"      <ul>\n"
"        <li><a href=\"control.html\">Control</a></li>\n"
"        <li><a href=\"settings.html\">Settings</a></li>\n"
"        <li><a href=\"help.html\">Help</a></li>\n"
"        <li><a href=\"user_manual.html\">User Manual</a></li>\n"
"        <li><a href=\"programming_manual.html\">Programming Manual</a></li>\n"
"      </ul>\n"
"    </div>\n"
"    <div class=\"main-content\">\n"
"      <h2>User Manual</h2>\n"
"      <p>This manual explains how to operate the ENERGIS PDU:</p>\n"
"      <ul>\n"
"        <li>Turning channels on/off via sliding toggles</li>\n"
"        <li>Monitoring voltage, current, uptime, and power</li>\n"
"        <li>Configuring network and device settings</li>\n"
"        <li>Troubleshooting tips</li>\n"
"      </ul>\n"
"    </div>\n"
"  </div>\n"
"</body>\n"
"</html>\n";

// programming_manual.html
const char programming_manual_html[] =
"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"  <meta charset=\"UTF-8\" />\n"
"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"  <title>ENERGIS PDU - Programming Manual</title>\n"
"  <style>\n"
"    * { margin: 0; padding: 0; box-sizing: border-box; font-family: sans-serif; }\n"
"    body { background-color: #1a1d23; color: #e4e4e4; }\n"
"    a { text-decoration: none; color: #aaa; } a:hover { color: #fff; }\n"
"    .topbar { width: 100%; height: 50px; background-color: #242731; display: flex; align-items: center; padding: 0 20px; }\n"
"    .topbar h1 { font-size: 1.2rem; color: #fff; }\n"
"    .container { display: flex; width: 100%; height: calc(100vh - 50px); }\n"
"    .sidebar { width: 220px; background-color: #2e323c; padding: 20px 0; }\n"
"    .sidebar ul { list-style: none; }\n"
"    .sidebar ul li { padding: 10px 20px; }\n"
"    .sidebar ul li:hover { background-color: #3b404d; }\n"
"    .main-content { flex: 1; padding: 20px; overflow-y: auto; }\n"
"    h2 { margin-bottom: 0.5rem; }\n"
"    p { margin: 0.5rem 0; }\n"
"    ul { margin-left: 20px; }\n"
"  </style>\n"
"</head>\n"
"<body>\n"
"  <div class=\"topbar\"><h1>ENERGIS PDU</h1></div>\n"
"  <div class=\"container\">\n"
"    <div class=\"sidebar\">\n"
"      <ul>\n"
"        <li><a href=\"control.html\">Control</a></li>\n"
"        <li><a href=\"settings.html\">Settings</a></li>\n"
"        <li><a href=\"help.html\">Help</a></li>\n"
"        <li><a href=\"user_manual.html\">User Manual</a></li>\n"
"        <li><a href=\"programming_manual.html\">Programming Manual</a></li>\n"
"      </ul>\n"
"    </div>\n"
"    <div class=\"main-content\">\n"
"      <h2>Programming Manual</h2>\n"
"      <p>This manual provides details on the programming interface for the ENERGIS PDU:</p>\n"
"      <ul>\n"
"        <li>RP2040 firmware details</li>\n"
"        <li>Communication with the W5500 Ethernet module</li>\n"
"        <li>EEPROM storage of settings</li>\n"
"        <li>Command formats and interfacing instructions</li>\n"
"      </ul>\n"
"    </div>\n"
"  </div>\n"
"</body>\n"
"</html>\n";

#endif // HTML_FILES_H
