/**
 * @file src/web_handlers/page_content.c
 * @author DvidMakesThings - David Sipos
 *
 * @version 1.0.0
 * @date 2025-11-07
 *
 * @details Stores HTML pages as const char arrays in flash memory.
 *
 * @project ENERGIS - The Managed PDU Project for 10-Inch Rack
 * @github https://github.com/DvidMakesThings/HW_10-In-Rack_PDU
 */

#include "../CONFIG.h"

/**
 * @brief HTML content for the Control page.
 *
 * This string contains the HTML markup for the Control page,
 * allowing users to toggle power channels and monitor data.
 */
const char control_html[] =
    "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\" /><meta name=\"viewport\" "
    "content=\"width=device-width,initial-scale=1.0\"><title>ENERGIS 8 Channel Managed PDU – "
    "Control</title><style>* "
    "{ margin: 0; padding: 0; box-sizing: border-box; font-family: sans-serif } body { background: "
    "#1a1d23; color: #e4e4e4 } a { text-decoration: none; color: #aaa } a:hover { color: #fff } "
    ".topbar { height: 50px; background: #242731; display: flex; align-items: center; padding: 0 "
    "20px } .topbar h1 { font-size: 1.2rem; color: #fff } .container { display: flex; height: "
    "calc(100vh - 50px) } .sidebar { width: 220px; background: #2e323c; padding: 20px 0 } .sidebar "
    "ul { list-style: none } .sidebar li { padding: 10px 20px } .sidebar li:hover { background: "
    "#3b404d } .main-content { flex: 1; padding: 20px; overflow-y: auto } table { width: 100%; "
    "border-collapse: collapse; margin-top: 1rem } th, td { text-align: left; padding: .75rem; "
    "border-bottom: 1px solid #3f4450 } th { background: #2e323c } .switch { position: relative; "
    "display: inline-block; width: 50px; height: 24px } .switch input { opacity: 0; width: 0; "
    "height: 0 } .slider { position: absolute; cursor: pointer; top: 0; left: 0; right: 0; bottom: "
    "0; background: #999; transition: .4s; border-radius: 24px } .slider:before { position: "
    "absolute; content: \"\"; height: 18px; width: 18px; left: 3px; bottom: 3px; background: #fff; "
    "transition: .4s; border-radius: 50% } input:checked+.slider { background: #3fa7ff } "
    "input:checked+.slider:before { transform: translateX(26px) } .btn { background: #3fa7ff; "
    "border: none; padding: 10px 16px; color: #fff; cursor: pointer; border-radius: 4px; "
    "font-size: .9rem; margin-right: 8px } .btn:hover { background: #1f8ae3 } .btn-green { "
    "background: #28a745 } .btn-green:hover { background: #218838 } .btn-red { background: #dc3545 "
    "} .btn-red:hover { background: #c82333 } .status { margin-top: 1rem; background: #2e323c; "
    "padding: 10px; border-radius: 4px }</style><script>let pendingChanges = new Set(); function "
    "updateStatus() { fetch('/api/status') .then(r =>r.json()) .then(data =>{ "
    "data.channels.forEach((ch, i) =>{ document.getElementById(`voltage-${i + 1}`).innerText = "
    "ch.voltage.toFixed(2); document.getElementById(`current-${i + 1}`).innerText = "
    "ch.current.toFixed(2); document.getElementById(`uptime-${i + 1}`).innerText = ch.uptime; "
    "document.getElementById(`power-${i + 1}`).innerText = ch.power.toFixed(2); if "
    "(!pendingChanges.has(i + 1)) document.getElementById(`toggle-${i + 1}`).checked = ch.state; "
    "}); document.getElementById('internal-temperature').innerText = "
    "data.internalTemperature.toFixed(1); document.getElementById('temp-unit').innerText = "
    "data.temperatureUnit || '°C'; document.getElementById('system-status').innerText = "
    "data.systemStatus; }) .catch(console.error); } function toggleChannel(c) { "
    "pendingChanges.add(c); } function applyChanges(e) { e.preventDefault(); let fd = new "
    "FormData(e.target), body = new URLSearchParams(); for (let [k] of fd) if "
    "(k.startsWith('channel')) { let i = +k.replace('channel', ''); if "
    "(document.getElementById(`toggle-${i}`).checked) body.append(k, 'on'); } "
    "fetch('/api/control', { "
    "method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: "
    "body.toString() }) .then(r =>{ if (!r.ok) throw ''; pendingChanges.clear(); updateStatus(); "
    "}) .catch(_ =>updateStatus()); } function setAll(state) { for (let i = 1; i<= 8; i++) { "
    "document.getElementById(`toggle-${i}`).checked = state; toggleChannel(i); } } "
    "window.addEventListener('load', () =>{ updateStatus(); setInterval(updateStatus, 3000); "
    "});</script></head><body><div class=\"topbar\"><h1>ENERGIS 8 Channel Managed "
    "PDU</h1></div><div "
    "class=\"container\"><nav class=\"sidebar\"><ul><li><a "
    "href=\"control.html\">Control</a></li><li><a href=\"settings.html\">Settings</a></li><li><a "
    "href=\"help.html\">Help</a></li><li><a href=\"user_manual.html\">User Manual</a></li><li><a "
    "href=\"automation_manual.html\">Automation Manual</a></li></ul></nav><main "
    "class=\"main-content\"><h2>Control</h2><p>Manage power channels and monitor "
    "data.</p><form method=\"post\" action=\"/api/control\" "
    "onsubmit=\"applyChanges(event)\"><table><tr><th>Channel</th><th>Switch</th><th>Voltage "
    "(V)</th><th>Current (A)</th><th>Uptime (s)</th><th>Power "
    "(W)</th></tr><tr><td>1</td><td><label class=\"switch\"><input id=\"toggle-1\" "
    "type=\"checkbox\" name=\"channel1\" onclick=\"toggleChannel(1)\"><span "
    "class=\"slider\"></span></label></td><td id=\"voltage-1\">--</td><td "
    "id=\"current-1\">--</td><td id=\"uptime-1\">--</td><td "
    "id=\"power-1\">--</td></tr><tr><td>2</td><td><label class=\"switch\"><input id=\"toggle-2\" "
    "type=\"checkbox\" name=\"channel2\" onclick=\"toggleChannel(2)\"><span "
    "class=\"slider\"></span></label></td><td id=\"voltage-2\">--</td><td "
    "id=\"current-2\">--</td><td id=\"uptime-2\">--</td><td "
    "id=\"power-2\">--</td></tr><tr><td>3</td><td><label class=\"switch\"><input id=\"toggle-3\" "
    "type=\"checkbox\" name=\"channel3\" onclick=\"toggleChannel(3)\"><span "
    "class=\"slider\"></span></label></td><td id=\"voltage-3\">--</td><td "
    "id=\"current-3\">--</td><td id=\"uptime-3\">--</td><td "
    "id=\"power-3\">--</td></tr><tr><td>4</td><td><label class=\"switch\"><input id=\"toggle-4\" "
    "type=\"checkbox\" name=\"channel4\" onclick=\"toggleChannel(4)\"><span "
    "class=\"slider\"></span></label></td><td id=\"voltage-4\">--</td><td "
    "id=\"current-4\">--</td><td id=\"uptime-4\">--</td><td "
    "id=\"power-4\">--</td></tr><tr><td>5</td><td><label class=\"switch\"><input id=\"toggle-5\" "
    "type=\"checkbox\" name=\"channel5\" onclick=\"toggleChannel(5)\"><span "
    "class=\"slider\"></span></label></td><td id=\"voltage-5\">--</td><td "
    "id=\"current-5\">--</td><td id=\"uptime-5\">--</td><td "
    "id=\"power-5\">--</td></tr><tr><td>6</td><td><label class=\"switch\"><input id=\"toggle-6\" "
    "type=\"checkbox\" name=\"channel6\" onclick=\"toggleChannel(6)\"><span "
    "class=\"slider\"></span></label></td><td id=\"voltage-6\">--</td><td "
    "id=\"current-6\">--</td><td id=\"uptime-6\">--</td><td "
    "id=\"power-6\">--</td></tr><tr><td>7</td><td><label class=\"switch\"><input id=\"toggle-7\" "
    "type=\"checkbox\" name=\"channel7\" onclick=\"toggleChannel(7)\"><span "
    "class=\"slider\"></span></label></td><td id=\"voltage-7\">--</td><td "
    "id=\"current-7\">--</td><td id=\"uptime-7\">--</td><td "
    "id=\"power-7\">--</td></tr><tr><td>8</td><td><label class=\"switch\"><input id=\"toggle-8\" "
    "type=\"checkbox\" name=\"channel8\" onclick=\"toggleChannel(8)\"><span "
    "class=\"slider\"></span></label></td><td id=\"voltage-8\">--</td><td "
    "id=\"current-8\">--</td><td id=\"uptime-8\">--</td><td "
    "id=\"power-8\">--</td></tr></table><br><button type=\"submit\" class=\"btn btn-green\">Apply "
    "Changes</button><button type=\"button\" class=\"btn\" style=\"margin-left:60px\" "
    "onclick=\"setAll(true)\">All On</button><button type=\"button\" class=\"btn btn-red\" "
    "onclick=\"setAll(false)\">All Off</button></form><div class=\"status\"><p><strong>Internal "
    "Temperature:</strong><span id=\"internal-temperature\">--</span><span "
    "id=\"temp-unit\">°C</span></p><p><strong>System Status:</strong><span "
    "id=\"system-status\">--</span></p></div></main></div></body></html>\n";

/**
 * @brief HTML content for the Settings page.
 *
 * This string contains the HTML markup for the Settings page,
 * allowing users to configure network, device, and temperature unit settings.
 */
const char settings_html[] =
    "<!DOCTYPE html><html><head><meta charset=\"UTF-8\"><meta name=\"viewport\" "
    "content=\"width=device-width,initial-scale=1.0\"><title>ENERGIS 8 Channel Managed PDU - "
    "Settings</title>"
    "<style>*{margin:0;padding:0;box-sizing:border-box;font-family:sans-serif}"
    "body{background:#1a1d23;color:#e4e4e4}a{color:#aaa;text-decoration:none}"
    "a:hover{color:#fff}.topbar{width:100%;height:50px;background:#242731;display:flex;"
    "align-items:center;padding:0 20px}.topbar h1{font-size:1.2rem;color:#fff}"
    ".container{display:flex;width:100%;height:calc(100vh - 50px)}"
    ".sidebar{width:220px;background:#2e323c;padding:20px 0}.sidebar ul{list-style:none}"
    ".sidebar ul li{padding:10px 20px}.sidebar ul li:hover{background:#3b404d}"
    ".main-content{flex:1;padding:20px;overflow-y:auto}h2{margin-bottom:.5rem}"
    "hr{border:none;border-top:1px solid #333;margin:1rem 0}"
    ".form-group{display:flex;align-items:center;margin-bottom:.75rem}"
    ".form-group label{width:160px;margin-right:10px}"
    ".form-group input[type=text],.form-group input[type=radio]{padding:8px;"
    "border:none;border-radius:4px}.form-group input[type=text]{flex:1;"
    "max-width:200px;margin-right:10px}.btn{background:#3fa7ff;border:none;"
    "padding:10px 16px;color:#fff;cursor:pointer;border-radius:4px;font-size:.9rem}"
    ".btn:hover{background:#1f8ae3}.manuals{margin-top:2rem}</style></head>"
    "<body><div class=\"topbar\"><h1>ENERGIS 8 Channel Managed PDU</h1></div><div "
    "class=\"container\">"
    "<nav class=\"sidebar\"><ul>"
    "<li><a href=\"control.html\">Control</a></li>"
    "<li><a href=\"settings.html\">Settings</a></li>"
    "<li><a href=\"help.html\">Help</a></li>"
    "<li><a href=\"user_manual.html\">User Manual</a></li>"
    "<li><a href=\"automation_manual.html\">Automation Manual</a></li>"
    "</ul></nav><main class=\"main-content\">"
    "<h2>Settings</h2><form method=\"post\" action=\"/api/settings\">"
    "<h3>Network Settings</h3><hr>"
    "<div class=\"form-group\"><label for=\"ip\">IP Address:</label>"
    "<input type=\"text\" id=\"ip\" name=\"ip\" value=\"%s\">"
    "</div>"
    "<div class=\"form-group\"><label for=\"gateway\">Default Gateway:</label>"
    "<input type=\"text\" id=\"gateway\" name=\"gateway\" value=\"%s\">"
    "</div>"
    "<div class=\"form-group\"><label for=\"subnet\">Subnet Mask:</label>"
    "<input type=\"text\" id=\"subnet\" name=\"subnet\" value=\"%s\">"
    "</div>"
    "<div class=\"form-group\"><label for=\"dns\">DNS Server:</label>"
    "<input type=\"text\" id=\"dns\" name=\"dns\" value=\"%s\">"
    "</div>"
    "<h3>Device Settings</h3><hr>"
    "<div class=\"form-group\"><label for=\"device_name\">Device Name:</label>"
    "<input type=\"text\" id=\"device_name\" name=\"device_name\" value=\"%s\">"
    "</div>"
    "<div class=\"form-group\"><label for=\"location\">Device Location:</label>"
    "<input type=\"text\" id=\"location\" name=\"location\" value=\"%s\">"
    "</div>"
    "<h3>Temperature Unit</h3><hr>"
    "<div class=\"form-group\">"
    "<input type=\"radio\" id=\"celsius\" name=\"temp_unit\" value=\"celsius\" %s>"
    "<label for=\"celsius\">Celsius</label>"
    "</div>"
    "<div class=\"form-group\">"
    "<input type=\"radio\" id=\"fahrenheit\" name=\"temp_unit\" value=\"fahrenheit\" %s>"
    "<label for=\"fahrenheit\">Fahrenheit</label>"
    "</div>"
    "<div class=\"form-group\">"
    "<input type=\"radio\" id=\"kelvin\" name=\"temp_unit\" value=\"kelvin\" %s>"
    "<label for=\"kelvin\">Kelvin</label>"
    "</div><br>"
    "<button type=\"submit\" class=\"btn\">Save Settings</button>"
    "</form>"
    "<div class=\"manuals\">"
    "<h3>Manuals</h3><hr>"
    "<p><a href=\"user_manual.html\">User Manual</a><br>"
    "<a href=\"automation_manual.html\">Programming &amp; Interfacing Manual</a></p>"
    "</div>"
    "</main></div></body></html>\n";

/**
 * @brief HTML content for the Help page.
 *
 * This string contains the HTML markup for the Help page,
 * providing guidance and links to manuals for the ENERGIS 8 Channel Managed PDU.
 */
const char help_html[] =
    "<!DOCTYPE html><html><head><meta charset=\"UTF-8\" /><meta name=\"viewport\" "
    "content=\"width=device-width, initial-scale=1.0\"><title>ENERGIS 8 Channel Managed PDU - "
    "Help</title><style>* { "
    "margin: 0; padding: 0; box-sizing: border-box; font-family: sans-serif; } body { "
    "background-color: #1a1d23; color: #e4e4e4; } a { text-decoration: none; color: #aaa; } "
    "a:hover { color: #fff; } .topbar { width: 100%; height: 50px; background-color: #242731; "
    "display: flex; align-items: center; padding: 0 20px; } .topbar h1 { font-size: 1.2rem; color: "
    "#fff; } .container { display: flex; width: 100%; height: calc(100vh - 50px); } .sidebar { "
    "width: 220px; background-color: #2e323c; padding: 20px 0; } .sidebar ul { list-style: none; } "
    ".sidebar ul li { padding: 10px 20px; } .sidebar ul li:hover { background-color: #3b404d; } "
    ".main-content { flex: 1; padding: 20px; overflow-y: auto; } h2 { margin-bottom: 0.5rem; } p { "
    "margin: 0.5rem 0; } ul { margin-left: 20px; } /* Secondary content sidebar layout inside main "
    "content */ .content-layout { display: flex; gap: 20px; align-items: flex-start; margin-top: "
    "0.5rem; } .content-sidebar { width: 230px; background-color: #2e323c; padding: 16px 16px 18px "
    "16px; /* Increased interior padding for airiness */ border-radius: 4px; font-size: 0.85rem; "
    "position: sticky; top: 10px; max-height: calc(100vh - 90px); overflow-y: auto; } "
    ".content-sidebar h3 { margin-top: 0; margin-bottom: 0.6rem; /* more space below heading */ "
    "font-size: 0.95rem; /* slightly larger */ } .content-sidebar h4 { margin: 0.9rem 0 0.45rem 0; "
    "/* larger separation between groups */ font-size: 0.78rem; /* compact label but airy "
    "surroundings */ text-transform: uppercase; letter-spacing: 0.05em; color: #c0c0c0; "
    "border-top: 1px solid #3a3f49; /* subtle divider */ padding-top: 0.65rem; } .content-sidebar "
    "ul { list-style: none; margin: 0 0 0.95rem 0; /* more spacing after each list block */ "
    "padding: 0; } .content-sidebar li { margin: 0.22rem 0 0.30rem; /* taller vertical rhythm */ "
    "line-height: 1.25rem; /* extra breathing room per item */ } .content-sidebar a { color: #ddd; "
    "font-size: 0.86rem; /* slightly larger for readability */ padding: 3px 6px; /* clickable "
    "padding */ border-radius: 4px; display: inline-block; /* allow padding background */ "
    "transition: background-color 120ms ease, color 120ms ease; } .content-sidebar a:hover { "
    "color: #fff; background-color: #3b404d; /* subtle hover chip */ } .content-body { flex: 1; "
    "min-width: 0; max-width: 800px; /* limit line length for readability; not centered per user "
    "preference */ margin: 0; /* align naturally with sidebar */ padding-right: 8px; /* slight "
    "inner right padding to balance */ } .section { margin-bottom: 1.75rem; /* more space between "
    "sections */ padding-bottom: 0.6rem; border-bottom: 1px solid #333842; } .section h3 { "
    "margin-top: 0.4rem; margin-bottom: 0.2rem; font-size: 1rem; } .section h4 { margin-top: "
    "0.6rem; margin-bottom: 0.2rem; font-size: 0.95rem; } /* Increase vertical rhythm in body text "
    "*/ .section p { margin: 0.75rem 0; /* more breathing room between paragraphs */ line-height: "
    "1.5; /* slightly taller line height */ } .section ul, .section ol { margin: 0.6rem 0 1.0rem "
    "1.1rem; /* add bottom space after lists */ padding-left: 0.6rem; /* indent list content "
    "slightly */ } .section ul li, .section ol li { margin: 0.35rem 0; /* space between list rows "
    "*/ line-height: 1.4; /* improve readability for list items */ } /* Justified body text for a "
    "more symmetric edge alignment */ .content-body p, .section p { text-align: justify; "
    "text-justify: inter-word; } /* Optional: justify list item text without affecting bullet "
    "alignment */ .section ul li { text-align: justify; text-justify: inter-word; } .tagline { "
    "font-size: 0.85rem; color: #c0c0c0; margin-top: 0.1rem; margin-bottom: 0.4rem; } .muted { "
    "color: #a0a0a0; font-size: 0.82rem; } .callout { border-left: 3px solid #4f46e5; "
    "background-color: #1f2230; padding: 8px 10px; margin: 0.5rem 0; font-size: 0.86rem; } "
    ".callout strong { color: #e5e7eb; } .warning { border-left-color: #f97373; background-color: "
    "#3b1f26; } pre { background-color: #111827; padding: 8px 10px; border-radius: 4px; "
    "overflow-x: auto; font-size: 0.8rem; margin: 0.45rem 0 0.7rem 0; white-space: pre; } code { "
    "font-family: Consolas, \"Fira Code\", monospace; } .quick-links { margin: 0.4rem 0 0.8rem 0; "
    "font-size: 0.82rem; } .quick-links a { margin-right: 10px; color: #ddd; } .quick-links "
    "a:hover { color: #fff; } @media (max-width: 900px) { .container { flex-direction: column; "
    "height: auto; } .sidebar { width: 100%; } .content-layout { flex-direction: column; } "
    ".content-sidebar { position: static; width: 100%; max-height: none; } "
    "}</style></head><body><div class=\"topbar\"><h1>ENERGIS 8 Channel Managed PDU</h1></div><div "
    "class=\"container\"><div class=\"sidebar\"><ul><li><a "
    "href=\"control.html\">Control</a></li><li><a href=\"settings.html\">Settings</a></li><li><a "
    "href=\"help.html\">Help</a></li><li><a href=\"user_manual.html\">User Manual</a></li><li><a "
    "href=\"automation_manual.html\">Automation Manual</a></li></ul></div><div "
    "class=\"main-content\"><div class=\"content-layout\"><div class=\"content-sidebar\"><h3>On "
    "this page</h3><h4>User guide</h4><ul><li><a href=\"#overview\">1. Overview &amp; "
    "safety</a></li><li><a href=\"#front-panel\">2. Front panel &amp; buttons</a></li><li><a "
    "href=\"#installation\">3. Installation &amp; wiring</a></li><li><a href=\"#web-ui\">4. Web "
    "interface</a></li><li><a href=\"#sleep-mode\">5. Power button &amp; sleep mode</a></li><li><a "
    "href=\"#troubleshooting\">6. Basic troubleshooting</a></li><li><a href=\"#firmware\">7. "
    "Firmware update &amp; specs</a></li></ul><h4>Automation &amp; integration</h4><ul><li><a "
    "href=\"#serial-cli\">8. USB serial console</a></li><li><a href=\"#http-api\">9. HTTP "
    "API</a></li><li><a href=\"#html-pages\">10. Built in HTML pages</a></li><li><a "
    "href=\"#metrics\">11. /metrics (OpenMetrics)</a></li><li><a href=\"#snmp\">12. "
    "SNMP</a></li><li><a href=\"#integration\">13. Integration examples</a></li><li><a "
    "href=\"#more-docs\">14. More documentation</a></li></ul></div><div "
    "class=\"content-body\"><div class=\"section\" id=\"overview\"><h3>1. Overview &amp; "
    "safety</h3><p class=\"tagline\">What the ENERGIS 8 Channel Managed PDU is, who should install "
    "it, and the most "
    "important limits.</p><div class=\"callout warning\"><strong>Warning:</strong>ENERGIS switches "
    "and distributes mains voltage. Incorrect installation or use can cause electric shock, fire, "
    "or damage to connected equipment. Only qualified personnel familiar with mains installation "
    "and local regulations should install and service the device.</div><h4>1.1 What ENERGIS "
    "is</h4><p>ENERGIS is an 8 channel managed power distribution unit for 10&nbsp;inch racks, lab "
    "benches and small installations. Each rear IEC&nbsp;C13 outlet can be switched individually "
    "and has per channel measurements for voltage, current, power and uptime.</p><p>You can "
    "operate the PDU:</p><ul><li>Locally from the front panel buttons and LEDs,</li><li>Via the "
    "built in web interface (<a href=\"control.html\">control.html</a>,<a "
    "href=\"settings.html\">settings.html</a>),</li><li>Over USB serial with a text "
    "console,</li><li>Through automation interfaces: HTTP API, SNMP and a Prometheus "
    "compatible<code>/metrics</code>endpoint.</li></ul><div class=\"quick-links\"><a "
    "href=\"#installation\">Installation</a><a href=\"#front-panel\">Front panel behavior</a><a "
    "href=\"#http-api\">HTTP API</a><a href=\"#metrics\">/metrics</a></div><h4>1.2 Intended "
    "use</h4><ul><li>Indoor IT, lab and test equipment compatible with local mains voltage and "
    "IEC&nbsp;C13 outlets.</li><li>Small racks and cabinets where individual outlet control and "
    "basic power monitoring are needed.</li></ul><p>ENERGIS is not an extension cord, surge "
    "protector, or safety / life support device.</p><h4>1.3 Electrical ratings "
    "(summary)</h4><ul><li>Input voltage: 85&nbsp;VAC to 305&nbsp;VAC, "
    "50/60&nbsp;Hz.</li><li>Maximum input current: 16&nbsp;A at the inlet.</li><li>Maximum per "
    "channel current: 16&nbsp;A per outlet, limited by connectors and wiring.</li><li>Total "
    "current of all active outlets must not exceed 16&nbsp;A.</li></ul><p>Do not daisy chain "
    "multiple PDUs from a single mains outlet and do not feed other multi way strips from "
    "ENERGIS.</p><h4>1.4 Grounding and environment</h4><ul><li>Connect the AC inlet only to a "
    "properly grounded mains outlet.</li><li>Protective earth is mandatory. Do not defeat or "
    "bypass earth connection.</li><li>Indoor use only, in dry, non corrosive environments without "
    "conductive dust.</li><li>Typical operating temperature: 0&nbsp;°C to 50&nbsp;°C. At higher "
    "temperatures, reduce load for reliability.</li></ul></div><div class=\"section\" "
    "id=\"front-panel\"><h3>2. Front panel &amp; button behavior</h3><p class=\"tagline\">How LEDs "
    "and buttons work for local control.</p><h4>2.1 Channel indicators</h4><p>Each channel "
    "(CH1–CH8) has a pair of LEDs:</p><ul><li><strong>Green LED:</strong>outlet state<ul><li>On: "
    "outlet is switched on and supplies mains voltage to the rear C13 connector.</li><li>Off: "
    "outlet is switched off.</li></ul></li><li><strong>Orange LED:</strong>selection "
    "indication<ul><li>Off: no selection window is active.</li><li>Blinking: this channel is "
    "currently selected in the 10&nbsp;s selection window.</li></ul></li></ul><p>Orange LEDs are "
    "only used while the selection window is open. Outside that time only the green on/off state "
    "is shown.</p><h4>2.2 Status LEDs</h4><ul><li><strong>PWR:</strong>internal power supply is "
    "within its expected range. If this LED is off, the device is not "
    "operating.</li><li><strong>LAN:</strong>Ethernet link detected. Indicates physical link, not "
    "full IP configuration.</li><li><strong>ERR:</strong>internal error has been detected. Clear "
    "it with a long press of the Set button. If it returns, see<a href=\"#troubleshooting\">Basic "
    "troubleshooting</a>.</li></ul><h4>2.3 Selection window logic</h4><p>The three front panel "
    "buttons use a time limited selection window to avoid accidental "
    "switching.</p><ul><li><strong>Opening the window:</strong><ul><li>A short press on any of the "
    "three buttons (Left, Right, Set) when idle opens a 10&nbsp;s selection window.</li><li>One "
    "channel is selected and its orange LED starts blinking.</li><li>No outlet state changes with "
    "this first press; it only opens the window.</li></ul></li><li><strong>While the window is "
    "open:</strong><ul><li><strong>Left / Right:</strong>move the selection to previous / next "
    "channel. The blinking orange LED follows and wraps between CH1 and CH8.</li><li><strong>Set "
    "(short press):</strong>toggles the selected outlet on/off. The green LED "
    "updates.</li><li><strong>Set (long press, approx. 1&nbsp;s):</strong>clears ERR. Does not "
    "change any outlet state.</li><li>Any valid button press restarts the 10&nbsp;s "
    "timeout.</li></ul></li><li><strong>Closing the window:</strong><ul><li>If there is no button "
    "activity for 10&nbsp;s, the selection window closes and all orange LEDs turn "
    "off.</li></ul></li></ul></div><div class=\"section\" id=\"sleep-mode\"><h3>3. Power button "
    "&amp; sleep mode</h3><p class=\"tagline\">How the dedicated power button behaves.</p><p>The "
    "front panel power button controls a low power sleep state for the whole "
    "unit.</p><ul><li><strong>Device active, long press (&gt; 2&nbsp;s):</strong>enters low power "
    "sleep.<ul><li>All outputs are turned off.</li><li>PWR LED blinks at 0.5&nbsp;Hz (1&nbsp;s on, "
    "1&nbsp;s off).</li><li>All normal functionality becomes unavailable until "
    "wakeup.</li></ul></li><li><strong>Device active, short press:</strong>no "
    "effect.</li><li><strong>Device in sleep, short press:</strong>wakes the device and returns to "
    "active mode. Normal operation resumes.</li><li><strong>Device in sleep, long "
    "press:</strong>no additional effect.</li></ul></div><div class=\"section\" "
    "id=\"installation\"><h3>4. Installation &amp; wiring</h3><p class=\"tagline\">Mounting, mains "
    "connection, load connection and optional USB.</p><div class=\"callout "
    "warning\"><strong>Important:</strong>All work on the mains supply must be done by qualified "
    "personnel. Always verify ratings and grounding before energizing the device.</div><h4>4.1 "
    "Mounting in a rack</h4><ul><li>Designed for 10&nbsp;inch racks and small cabinets, 1U "
    "height.</li><li>Use the mounting ears with suitable screws or cage nuts.</li><li>Avoid "
    "mechanical stress on front panel and connectors during installation.</li><li>Leave clearance "
    "for rear cables and some airflow. Keep LEDs and buttons visible.</li></ul><h4>4.2 Power "
    "connection</h4><ol><li>Verify local mains voltage matches the rating on the device "
    "label.</li><li>Connect the AC inlet to a properly grounded mains outlet using a suitable "
    "cable rated at 16&nbsp;A.</li><li>Check upstream protection (fuse or breaker) and wiring are "
    "appropriate for 16&nbsp;A maximum input current.</li><li>Once powered, verify that PWR LED is "
    "lit.</li></ol><h4>4.3 Connecting loads</h4><ul><li>Use IEC&nbsp;C14 cord sets or certified "
    "adapters for the rear C13 outlets.</li><li>Document which device is plugged into which "
    "channel (CH1–CH8).</li><li>Best practice: switch the outlet off before plugging or unplugging "
    "loads to minimise arcing and unintended reboots.</li><li>Keep total current within the "
    "16&nbsp;A limit and distribute high power loads across channels.</li><li>Do not daisy chain "
    "other PDUs or multi strips from ENERGIS outlets.</li></ul><h4>4.4 Network "
    "connection</h4><ol><li>Connect the RJ45 port to a switch/router using a standard Ethernet "
    "cable (CAT5 or better).</li><li>Confirm that the LAN LED is lit, indicating a physical "
    "link.</li><li>Use the IP address from the product label or from your "
    "documentation.</li><li>From a host in the same subnet, "
    "open<code>http://&lt;device-ip&gt;/</code>in a browser to reach the web UI.</li></ol><h4>4.5 "
    "USB connection (console)</h4><ul><li>Connect the front USB&nbsp;C port to a "
    "computer.</li><li>The OS will detect a USB CDC (virtual COM) device; usually no extra driver "
    "is required.</li><li>Use 115200&nbsp;baud, 8&nbsp;data bits, no parity, 1&nbsp;stop "
    "bit.</li><li>Use the console for commissioning, diagnostics and advanced configuration. "
    "Normal daily use can be done via web UI and front panel.</li></ul></div><div "
    "class=\"section\" id=\"web-ui\"><h3>5. Web interface</h3><p class=\"tagline\">Browser based "
    "control and configuration.</p><h4>5.1 Accessing the web UI</h4><ol><li>Ensure PWR and LAN "
    "LEDs indicate that the unit is powered and linked.</li><li>Make sure your computer is in the "
    "same IP subnet or routing is configured "
    "appropriately.</li><li>Open<code>http://&lt;device-ip&gt;/</code>or<code>http://"
    "&lt;device-ip&gt;/control.html</code>in a modern browser.</li></ol><h4>5.2 Control page (<a "
    "href=\"control.html\">control.html</a>)</h4><ul><li>Shows one row per outlet "
    "(CH1–CH8).</li><li>Per channel:<ul><li>Outlet state (ON/OFF) and control to toggle the "
    "relay.</li><li>Measured voltage, current, power and channel uptime.</li></ul></li><li>Values "
    "update periodically from internal telemetry. Measurements are cached; they do not change "
    "instantly at the moment of switching.</li></ul><h4>5.3 Settings page (<a "
    "href=\"settings.html\">settings.html</a>)</h4><ul><li><strong>Device "
    "identification:</strong>name, location, temperature unit.</li><li><strong>Network "
    "configuration:</strong>IP address, subnet mask, gateway, DNS server.</li></ul><p>After "
    "changing IP parameters, the device stores them and reboots. You then reach it under the new "
    "IP.</p><div class=\"callout warning\"><strong>Caution:</strong>After changing "
    "IP/subnet/gateway, the PDU becomes unreachable at the old address. Make sure you know the new "
    "configuration and how to access the device again.</div></div><div class=\"section\" "
    "id=\"troubleshooting\"><h3>6. Basic troubleshooting</h3><p class=\"tagline\">Quick checks for "
    "common on site issues.</p><h4>6.1 Web UI not reachable</h4><ol><li><strong>Check "
    "LEDs:</strong>PWR must be on; LAN must be on or blinking.</li><li><strong>Check "
    "cabling:</strong>Ethernet cable properly connected; switch port "
    "enabled.</li><li><strong>Check IP:</strong>confirm you are using the correct IP and that your "
    "host is in the same network.</li><li><strong>Ping test:</strong>run<code>ping "
    "&lt;device-ip&gt;</code>from a PC. If it fails, double check network "
    "settings.</li><li><strong>Errors:</strong>if ERR is lit, long press Set to clear. Power cycle "
    "the device if needed.</li></ol><h4>6.2 Outlets do not switch</h4><ul><li>Confirm you are "
    "addressing the correct channel for the physical outlet.</li><li>Check ERR LED and clear it "
    "with a long press on Set.</li><li>Verify upstream protection (breaker/fuse) has not "
    "tripped.</li><li>Ensure total load does not exceed 16&nbsp;A.</li></ul><h4>6.3 Measurements "
    "show zero</h4><ul><li>Check the outlet’s green LED is on and a real load is "
    "connected.</li><li>Wait a few seconds; telemetry is updated periodically.</li><li>Very light "
    "loads may show very low or zero current and power.</li></ul><h4>6.4 Forgot the IP "
    "address</h4><ul><li>Check the label on the underside for factory default network "
    "settings.</li><li>Check installation notes where the configured IP might be "
    "recorded.</li><li>If needed, network settings can be reset via the console, restoring "
    "defaults (see<a href=\"#serial-cli\">USB serial console</a>).</li></ul></div><div "
    "class=\"section\" id=\"firmware\"><h3>7. Firmware update &amp; technical summary</h3><p "
    "class=\"tagline\">Safe firmware update and key technical data.</p><h4>7.1 Firmware update via "
    "UF2</h4><ol><li>Obtain the correct<code>.uf2</code>file for your hardware "
    "revision.</li><li>Connect ENERGIS via USB&nbsp;C to a computer. Mains can stay connected "
    "during the update.</li><li>Open a serial terminal (see<a href=\"#serial-cli\">USB serial "
    "console</a>) and run the<code>BOOTSEL</code>command, or use the documented button sequence to "
    "enter boot mode.</li><li>The device appears as a USB mass storage drive.</li><li>Copy "
    "the<code>.uf2</code>file onto the drive and wait until it finishes and the drive "
    "disappears.</li><li>ENERGIS restarts with the new firmware. Verify operation via the web UI "
    "or the console command<code>SYSINFO</code>.</li></ol><div class=\"callout "
    "warning\"><strong>Caution:</strong>Do not disconnect power or USB while copying "
    "the<code>.uf2</code>file. Interrupting the update can corrupt the image and require "
    "recovery.</div><h4>7.2 Technical data (short)</h4><ul><li>Input: 85&nbsp;VAC to 305&nbsp;VAC, "
    "50/60&nbsp;Hz, 16&nbsp;A max.</li><li>Outputs: 8&nbsp;x IEC&nbsp;C13, each up to 16&nbsp;A, "
    "max 16&nbsp;A total.</li><li>Form factor: 10&nbsp;inch rack, 1U.</li><li>Interfaces: "
    "RJ45&nbsp;10/100 Ethernet, USB&nbsp;C (USB CDC console).</li><li>Per channel metering: "
    "HLW8032 based, used internally by firmware.</li></ul></div><div class=\"section\" "
    "id=\"serial-cli\"><h3>8. USB serial console</h3><p class=\"tagline\">Text commands for "
    "diagnostics and configuration.</p><h4>8.1 Access</h4><ul><li>Connect USB&nbsp;C to a "
    "host.</li><li>Open a serial terminal at 115200&nbsp;baud, "
    "8N1.</li><li>Type<code>HELP</code>to see supported commands.</li></ul><h4>8.2 Typical "
    "commands</h4><ul><li><code>HELP</code>– list commands.</li><li><code>SYSINFO</code>– show "
    "firmware version and basic system info.</li><li><code>GET_TEMP</code>– MCU "
    "temperature.</li><li><code>REBOOT</code>– restart the device.</li><li><code>BOOTSEL</code>– "
    "enter USB mass storage mode for firmware update.</li><li><code>CLR_ERR</code>– clear internal "
    "error (same as long press Set).</li><li><code>RFS</code>– restore factory settings (network "
    "and preferences).</li></ul><h4>8.3 Outlet control</h4><ul><li><code>SET_CH &lt;ch&gt; "
    "&lt;STATE&gt;</code>– set channel<code>ch</code>(1–8) to ON/OFF or ALL:<ul><li>State can "
    "be<code>0</code>/<code>OFF</code>or<code>1</code>/<code>ON</code>, or<code>ALL</code>where "
    "supported.</li></ul></li><li><code>GET_CH &lt;ch&gt;</code>– read state of a channel or all "
    "channels.</li><li><code>READ_HLW8032</code>– read meter snapshot for all "
    "channels.</li></ul><h4>8.4 Network configuration</h4><ul><li><code>NETINFO</code>– prints "
    "current IP, subnet, gateway, DNS.</li><li><code>SET_IP &lt;ip&gt;</code>,<code>SET_SN "
    "&lt;mask&gt;</code>,<code>SET_GW &lt;gw&gt;</code>,<code>SET_DNS &lt;dns&gt;</code>– set "
    "network parameters.</li><li><code>CONFIG_NETWORK ip$sn$gw$dns</code>– configure all network "
    "parameters in one command.</li></ul></div><div class=\"section\" id=\"http-api\"><h3>9. HTTP "
    "API</h3><p class=\"tagline\">JSON and form based endpoints for remote control and "
    "configuration.</p><p>The embedded HTTP server listens on port&nbsp;80 and exposes JSON "
    "endpoints under<code>/api/...</code>. All responses use HTTP/1.1 and include<code>Connection: "
    "close</code>.</p><h4>9.1 GET /api/status</h4><p>Returns overall status and per channel "
    "telemetry.</p><ul><li><code>channels</code>– array of 8 objects, each "
    "containing<code>voltage</code>,<code>current</code>,<code>uptime</code>,<code>power</"
    "code>,<code>state</code>.</li><li><code>internalTemperature</code>– MCU die "
    "temperature.</li><li><code>temperatureUnit</code>– such "
    "as<code>\"°C\"</code>.</li><li><code>systemStatus</code>– short status "
    "string.</li></ul><pre><code>curl http://&lt;device-ip&gt;/api/status</code></pre><h4>9.2 POST "
    "/api/control</h4><p>Control relays using simple form encoded data. Each field is "
    "named<code>channelN</code>for N&nbsp;=&nbsp;1..8.</p><ul><li><code>channelN=on</code>– turn "
    "channel N on.</li><li>Omit the field or set it to an empty string to turn the channel "
    "off.</li></ul><pre><code># Turn channels 1 and 3 on, all others off curl -X POST "
    "\"http://&lt;device-ip&gt;/api/control\" \ --data "
    "\"channel1=on&amp;channel3=on\"</code></pre><h4>9.3 GET /api/settings</h4><p>Returns current "
    "network configuration and user preferences in JSON.</p><ul><li>Typical "
    "fields:<code>ip</code>,<code>subnet</code>,<code>gateway</code>,<code>dns</"
    "code>,<code>device_name</code>,<code>location</code>,<code>temp_unit</"
    "code>,<code>temperature</code>.</li></ul><pre><code>curl "
    "http://&lt;device-ip&gt;/api/settings</code></pre><h4>9.4 POST /api/settings</h4><p>Updates "
    "network parameters and user preferences. Uses form encoded data.</p><pre><code>curl -X POST "
    "\"http://&lt;device-ip&gt;/api/settings\" \ --data "
    "\"ip=192.168.0.12&amp;subnet=255.255.255.0&amp;gateway=192.168.0.1&amp;dns=8.8.8.8&amp;device_"
    "name=ENERGIS&amp;location=Rack1&amp;temp_unit=celsius\"</code></pre><p>On success, the device "
    "stores the configuration, replies with 204&nbsp;No&nbsp;Content and then "
    "reboots.</p></div><div class=\"section\" id=\"html-pages\"><h3>10. Built in HTML pages</h3><p "
    "class=\"tagline\">Small static pages served directly by the "
    "PDU.</p><ul><li><strong>control.html</strong>– main outlet control and "
    "monitoring.</li><li><strong>settings.html</strong>– network and basic "
    "configuration.</li><li><strong>help.html</strong>– this offline help "
    "page.</li><li><strong>user_manual.html</strong>– landing page for the full User "
    "Manual.</li><li><strong>automation_manual.html</strong>– landing page for "
    "automation/programming documentation.</li></ul></div><div class=\"section\" "
    "id=\"metrics\"><h3>11. /metrics (OpenMetrics / Prometheus)</h3><p class=\"tagline\">Text "
    "based metrics endpoint for monitoring systems.</p><h4>11.1 "
    "Endpoint</h4><p>The<code>/metrics</code>endpoint exposes metrics in Prometheus/OpenMetrics "
    "text format.</p><pre><code>curl http://&lt;device-ip&gt;/metrics</code></pre><h4>11.2 Global "
    "metrics (examples)</h4><ul><li><code>energis_up</code>– gauge, 1 if the metrics handler is "
    "healthy.</li><li><code>energis_build_info{version,serial}</code>– gauge always 1, with labels "
    "identifying the build.</li><li><code>energis_uptime_seconds_total</code>– counter, total "
    "uptime in seconds.</li><li><code>energis_internal_temperature_celsius</code>– gauge, MCU "
    "temperature.</li><li><code>energis_vusb_volts</code>,<code>energis_vsupply_volts</code>– "
    "gauges, internal rails.</li></ul><h4>11.3 Per channel metrics (examples)</h4><p>Each channel "
    "has "
    "label<code>{ch=\"1\"}</code>to<code>{ch=\"8\"}</code>.</"
    "p><ul><li><code>energis_channel_state{ch}</code>– gauge, 1 for on, 0 for "
    "off.</li><li><code>energis_channel_telemetry_valid{ch}</code>– gauge, 1 if cached telemetry "
    "is fresh.</li><li><code>energis_channel_voltage_volts{ch}</code>– "
    "gauge.</li><li><code>energis_channel_current_amps{ch}</code>– "
    "gauge.</li><li><code>energis_channel_power_watts{ch}</code>– "
    "gauge.</li><li><code>energis_channel_energy_watt_hours_total{ch}</code>– counter, accumulated "
    "energy.</li></ul><p>Metrics are produced from cached meter data and never perform blocking "
    "I/O in the handler. If the output would exceed the internal buffer, the handler returns "
    "HTTP&nbsp;503 to signal an error instead of emitting partial metrics.</p><h4>11.4 Prometheus "
    "configuration example</h4><pre><code>scrape_configs: - job_name: 'energis-pdu' metrics_path: "
    "/metrics scrape_interval: 15s static_configs: - targets: ['192.168.0.22:80'] labels: "
    "location: 'rack-1' device: 'pdu-main'</code></pre></div><div class=\"section\" "
    "id=\"snmp\"><h3>12. SNMP</h3><p class=\"tagline\">SNMPv1 agent for state control and "
    "telemetry.</p><h4>12.1 Overview</h4><ul><li>SNMP version: "
    "v1.</li><li>Community:<code>public</code>.</li><li>MIB-II system group "
    "implemented.</li><li>Private enterprise "
    "subtree:<code>1.3.6.1.4.1.19865</code>.</li></ul><h4>12.2 System OIDs "
    "(MIB-II)</h4><ul><li><code>1.3.6.1.2.1.1.1.0</code>–<code>sysDescr</code>, descriptive "
    "text.</li><li><code>1.3.6.1.2.1.1.2.0</code>–<code>sysObjectID</code>, set to the enterprise "
    "ID.</li><li><code>1.3.6.1.2.1.1.3.0</code>–<code>sysUpTime</code>.</"
    "li><li><code>1.3.6.1.2.1.1.4.0</code>–<code>sysContact</code>.</"
    "li><li><code>1.3.6.1.2.1.1.5.0</code>–<code>sysName</code>, often serial "
    "number.</li><li><code>1.3.6.1.2.1.1.6.0</code>–<code>sysLocation</code>.</"
    "li><li><code>1.3.6.1.2.1.1.7.0</code>–<code>sysServices</code>.</li></ul><h4>12.3 Outlet "
    "control OIDs</h4><p>Per channel outlet state is exposed as INTEGER under the enterprise "
    "subtree:</p><ul><li><code>1.3.6.1.4.1.19865.2.&lt;ch&gt;.0</code>with<code>&lt;ch&gt; = "
    "1..8</code>.</li></ul><p>Behavior:</p><ul><li>GET returns 0 for off, 1 for on.</li><li>SET 0 "
    "turns the channel off.</li><li>SET non zero turns the channel on.</li></ul><h4>12.4 Group "
    "control OIDs</h4><ul><li><code>1.3.6.1.4.1.19865.2.9.0</code>– All OFF:<ul><li>GET: 1 only if "
    "all channels are off.</li><li>SET: any non zero value forces all channels "
    "off.</li></ul></li><li><code>1.3.6.1.4.1.19865.2.10.0</code>– All ON:<ul><li>GET: 1 only if "
    "all channels are on.</li><li>SET: any non zero value forces all channels "
    "on.</li></ul></li></ul><h4>12.5 Telemetry via SNMP</h4><p>Per channel telemetry is encoded as "
    "short strings under<code>1.3.6.1.4.1.19865.5</code>:</p><ul><li>Voltage "
    "(V):<code>1.3.6.1.4.1.19865.5.&lt;ch&gt;.1.0</code>, "
    "e.g.<code>\"230.12\"</code>.</li><li>Current "
    "(A):<code>1.3.6.1.4.1.19865.5.&lt;ch&gt;.2.0</code>, "
    "e.g.<code>\"0.534\"</code>.</li><li>Power "
    "(W):<code>1.3.6.1.4.1.19865.5.&lt;ch&gt;.3.0</code>, e.g.<code>\"85.3\"</code>.</li><li>Power "
    "factor:<code>1.3.6.1.4.1.19865.5.&lt;ch&gt;.4.0</code>, "
    "e.g.<code>\"0.998\"</code>.</li><li>Energy "
    "(kWh):<code>1.3.6.1.4.1.19865.5.&lt;ch&gt;.5.0</code>.</li><li>Channel uptime "
    "(s):<code>1.3.6.1.4.1.19865.5.&lt;ch&gt;.6.0</code>.</li></ul><p>All values are served from "
    "cached internal meter data and do not trigger blocking operations in the SNMP "
    "handler.</p></div><div class=\"section\" id=\"integration\"><h3>13. Integration "
    "examples</h3><p class=\"tagline\">Using ENERGIS with scripts and monitoring "
    "systems.</p><h4>13.1 Simple shell control with curl</h4><pre><code># Turn channel 2 on from a "
    "shell script curl -s -o /dev/null -X POST \"http://&lt;device-ip&gt;/api/control\" \ --data "
    "\"channel2=on\"</code></pre><h4>13.2 Periodic status logging</h4><pre><code># Log JSON status "
    "every minute (example cron entry) * * * * * curl -s \"http://&lt;device-ip&gt;/api/status\" "
    "&gt;&gt; /var/log/energis_status.json</code></pre><h4>13.3 Prometheus /metrics "
    "scraping</h4><pre><code>scrape_configs: - job_name: 'energis-pdu' metrics_path: /metrics "
    "scrape_interval: 15s static_configs: - targets: ['192.168.0.22:80'] labels: location: "
    "'rack-1'</code></pre><h4>13.4 SNMP in a network monitoring tool</h4><ul><li>Add ENERGIS as an "
    "SNMPv1 device with community<code>public</code>.</li><li>Graph the outlet state OIDs "
    "under<code>1.3.6.1.4.1.19865.2</code>(0/1) and telemetry values "
    "under<code>1.3.6.1.4.1.19865.5</code>.</li><li>Use All ON / All OFF OIDs to build basic "
    "control buttons.</li></ul></div><div class=\"section\" id=\"more-docs\"><h3>14. More "
    "documentation</h3><p class=\"tagline\">Where to find the full manuals and project "
    "details.</p><p>This help page is an embedded summary. For full detail, use:</p><ul><li><a "
    "href=\"user_manual.html\">User Manual</a>– complete installation, safety and technical "
    "data.</li><li><a href=\"automation_manual.html\">Programming &amp; Automation Manual</a>– "
    "protocol details, OID tables, and extended examples.</li></ul><p>Project sources, issue "
    "tracking and firmware releases are available through the official repository referenced in "
    "the printed documentation and product "
    "label.</p></div></div></div></div></div></body></html>\n";

/**
 * @brief HTML content for the User Manual page.
 *
 * This string contains the HTML markup for the User Manual page,
 * embedding the user manual PDF and providing a download link.
 */
const char user_manual_html[] =
    "<!DOCTYPE html><html><head><meta charset=\"UTF-8\" /><meta name=\"viewport\" "
    "content=\"width=device-width, initial-scale=1.0\"><title>ENERGIS 8 Channel Managed PDU – User "
    "Manual</title><style>* { margin: 0; padding: 0; box-sizing: border-box; font-family: "
    "sans-serif; } body { background: #1a1d23; color: #e4e4e4; } a { color: #aaa; text-decoration: "
    "none; } a:hover { color: #fff; } .topbar { height: 50px; background: #242731; display: flex; "
    "align-items: center; padding: 0 20px; } .topbar h1 { font-size: 1.2rem; color: #fff; } "
    ".container { display: flex; height: calc(100vh - 50px); } .sidebar { width: 220px; "
    "background: #2e323c; padding: 20px 0; } .sidebar ul { list-style: none; } .sidebar li { "
    "padding: 10px 20px; } .sidebar li:hover { background: #3b404d; } .sidebar a { color: #ccc; } "
    ".sidebar a:hover { color: #fff; } .content { flex: 1; display: flex; flex-direction: column; "
    "} .pdf-container { flex: 1; border: 1px solid #444; } .note { padding: 0.5rem; text-align: "
    "right; font-size: 0.9rem; }</style></head><body><div class=\"topbar\"><h1>ENERGIS 8 Channel "
    "Managed PDU</h1></div><div class=\"container\"><div class=\"sidebar\"><ul><li><a "
    "href=\"control.html\">Control</a></li><li><a href=\"settings.html\">Settings</a></li><li><a "
    "href=\"help.html\">Help</a></li><li><a href=\"user_manual.html\">User Manual</a></li><li><a "
    "href=\"automation_manual.html\">Automation Manual</a></li></ul></div><div "
    "class=\"content\"><div class=\"pdf-container\"><iframe "
    "src=\"https://dvidmakesthings.github.io/HW_10-In-Rack_PDU/Manuals/"
    "ENERGIS_UserManual_rev_1.0.0.pdf\" width=\"100%\" height=\"100%\" "
    "frameborder=\"0\"></iframe></div><p class=\"note\">If your browser does not display the PDF, "
    "you can download it directly<a "
    "href=\"https://dvidmakesthings.github.io/HW_10-In-Rack_PDU/Manuals/"
    "ENERGIS_UserManual_rev_1.0.0.pdf\" "
    "target=\"_blank\">here</a>.</p></div></div></body></html>\n";

/**
 * @brief HTML content for the Automation Manual page.
 *
 * This string contains the HTML markup for the Automation Manual page,
 * embedding the Automation Manual PDF and providing a download link.
 */
const char automation_manual_html[] =
    "<!DOCTYPE html><html><head><meta charset=\"UTF-8\" /><meta name=\"viewport\" "
    "content=\"width=device-width, initial-scale=1.0\"><title>ENERGIS 8 Channel Managed PDU – "
    "Programming "
    "Manual</title><style>* { margin: 0; padding: 0; box-sizing: border-box; font-family: "
    "sans-serif; } body { background: #1a1d23; color: #e4e4e4; } a { color: #aaa; text-decoration: "
    "none; } a:hover { color: #fff; } .topbar { height: 50px; background: #242731; display: flex; "
    "align-items: center; padding: 0 20px; } .topbar h1 { font-size: 1.2rem; color: #fff; } "
    ".container { display: flex; height: calc(100vh - 50px); } .sidebar { width: 220px; "
    "background: #2e323c; padding: 20px 0; } .sidebar ul { list-style: none; } .sidebar li { "
    "padding: 10px 20px; } .sidebar li:hover { background: #3b404d; } .sidebar a { color: #ccc; } "
    ".sidebar a:hover { color: #fff; } /* Right-side area */ .content { flex: 1; display: flex; "
    "flex-direction: column; } .pdf-container { flex: 1; border: 1px solid #444; } .note { "
    "padding: 0.5rem; text-align: right; font-size: 0.9rem; }</style></head><body><div "
    "class=\"topbar\"><h1>ENERGIS 8 Channel Managed PDU</h1></div><div class=\"container\"><div "
    "class=\"sidebar\"><ul><li><a href=\"control.html\">Control</a></li><li><a "
    "href=\"settings.html\">Settings</a></li><li><a href=\"help.html\">Help</a></li><li><a "
    "href=\"user_manual.html\">User Manual</a></li><li><a "
    "href=\"automation_manual.html\">Automation Manual</a></li></ul></div><div "
    "class=\"content\"><div class=\"pdf-container\"><iframe "
    "src=\"https://dvidmakesthings.github.io/HW_10-In-Rack_PDU/Manuals/"
    "ENERGIS_AutomationManual_rev_1.0.0.pdf\" width=\"100%\" height=\"100%\" "
    "frameborder=\"0\"></iframe></div><p class=\"note\">If your browser does not display the PDF, "
    "you can download it directly<a "
    "href=\"https://dvidmakesthings.github.io/HW_10-In-Rack_PDU/Manuals/"
    "ENERGIS_AutomationManual_rev_1.0.0.pdf\" "
    "target=\"_blank\">here</a>.</p></div></div></body></html>\n";

/**
 * @brief Gets the HTML content for a requested page
 * @param request The HTTP request line (e.g., "GET /api/control.html HTTP/1.1")
 * @return Pointer to the HTML content, or control.html as default
 * @note Routes HTTP requests to appropriate HTML page content
 */
const char *get_page_content(const char *request) {
    if (strstr(request, "GET /settings.html"))
        return settings_html;
    else if (strstr(request, "GET /help.html"))
        return help_html;
    else if (strstr(request, "GET /user_manual.html"))
        return user_manual_html;
    else if (strstr(request, "GET /automation_manual.html"))
        return automation_manual_html;
    else if (strstr(request, "GET /"))
        return control_html;

    /* Default to control page */
    return control_html;
}
