#ifndef HTML_SETTINGS_H
#define HTML_SETTINGS_H

const char settings_html[] =
"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"  <meta charset=\"UTF-8\" />\n"
"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"  <title>ENERGIS PDU - Settings</title>\n"
"  <style>\n"
"    * { margin: 0; padding: 0; box-sizing: border-box; font-family: sans-serif; }\n"
"    body { background-color: #1a1d23; color: #e4e4e4; }\n"
"    a { text-decoration: none; color: #aaa; } a:hover { color: #fff; }\n"
"    .topbar { width: 100%; height: 50px; background-color: #242731; display: flex; align-items: center; padding: 0 20px; }\n"
"    .topbar h1 { font-size: 1.2rem; color: #fff; }\n"
"    .container { display: flex; width: 100%; height: calc(100vh - 50px); }\n"
"    .sidebar { width: 220px; background-color: #2e323c; padding: 20px 0; }\n"
"    .sidebar ul { list-style: none; }\n"
"    .sidebar ul li { padding: 10px 20px; }\n"
"    .sidebar ul li:hover { background-color: #3b404d; }\n"
"    .main-content { flex: 1; padding: 20px; overflow-y: auto; }\n"
"    h2 { margin-bottom: 0.5rem; }\n"
"    p { margin: 0.5rem 0; }\n"
"    .status { margin-top: 1rem; background-color: #2e323c; padding: 10px; border-radius: 4px; }\n"
"    input, select, textarea { padding: 8px; margin-top: 4px; margin-bottom: 8px; border: none; border-radius: 4px; }\n"
"    .btn { background-color: #3fa7ff; border: none; padding: 10px 16px; color: #fff; cursor: pointer; border-radius: 4px; font-size: 0.9rem; }\n"
"    .btn:hover { background-color: #1f8ae3; }\n"
"    table { width: 100%; border-collapse: collapse; margin-top: 1rem; }\n"
"    th, td { text-align: left; padding: 0.75rem; border-bottom: 1px solid #3f4450; }\n"
"    th { background-color: #2e323c; }\n"
"    /* New styles for aligned form inputs */\n"
"    .form-group {\n"
"      display: flex;\n"
"      align-items: center;\n"
"      margin-bottom: 8px;\n"
"    }\n"
"    .form-group label {\n"
"      width: 160px;\n"
"      margin-right: 10px;\n"
"    }\n"
"    .form-group input[type=\"text\"] {\n"
"      flex: 1;\n"
"      max-width: 200px;\n"
"    }\n"
"  </style>\n"
"</head>\n"
"<body>\n"
"  <div class=\"topbar\"><h1>ENERGIS PDU</h1></div>\n"
"  <div class=\"container\">\n"
"    <div class=\"sidebar\">\n"
"      <ul>\n"
"        <li><a href=\"control.html\">Control</a></li>\n"
"        <li><a href=\"settings.html\">Settings</a></li>\n"
"        <li><a href=\"help.html\">Help</a></li>\n"
"        <li><a href=\"user_manual.html\">User Manual</a></li>\n"
"        <li><a href=\"programming_manual.html\">Programming Manual</a></li>\n"
"      </ul>\n"
"    </div>\n"
"    <div class=\"main-content\">\n"
"      <h2>Settings</h2>\n"
"      <form method=\"post\" action=\"/settings\">\n"
"        <h3>Network Settings</h3>\n"
"        <hr color=\"#333333\">\n"
"        <div class=\"form-group\">\n"
"          <label for=\"ip\">IP Address:</label>\n"
"          <input type=\"text\" id=\"ip\" name=\"ip\" value=\"192.168.1.100\">\n"
"        </div>\n"
"        <div class=\"form-group\">\n"
"          <label for=\"gateway\">Default Gateway:</label>\n"
"          <input type=\"text\" id=\"gateway\" name=\"gateway\" value=\"192.168.1.1\">\n"
"        </div>\n"
"        <div class=\"form-group\">\n"
"          <label for=\"subnet\">Subnet Mask:</label>\n"
"          <input type=\"text\" id=\"subnet\" name=\"subnet\" value=\"255.255.255.0\">\n"
"        </div>\n"
"        <h3>Device Settings</h3>\n"
"        <hr color=\"#333333\">\n"
"        <div class=\"form-group\">\n"
"          <label for=\"device_name\">Device Name:</label>\n"
"          <input type=\"text\" id=\"device_name\" name=\"device_name\" value=\"ENERGIS\">\n"
"        </div>\n"
"        <div class=\"form-group\">\n"
"          <label for=\"location\">Device Location:</label>\n"
"          <input type=\"text\" id=\"location\" name=\"location\" value=\"Server Room\">\n"
"        </div>\n"
"        <h3>Time Settings</h3>\n"
"        <hr color=\"#333333\">\n"
"        <div class=\"form-group\">\n"
"          <label for=\"timezone\">Timezone:</label>\n"
"          <input type=\"text\" id=\"timezone\" name=\"timezone\" value=\"UTC\">\n"
"        </div>\n"
"        <div class=\"form-group\">\n"
"          <label for=\"time\">Time (HH:MM:SS):</label>\n"
"          <input type=\"text\" id=\"time\" name=\"time\" value=\"12:00:00\">\n"
"        </div>\n"
"        <h3>Security Settings</h3>\n"
"        <hr color=\"#333333\">\n"
"        <div class=\"form-group\">\n"
"          <label for=\"autologout\">Auto Logout (min, 0 = off):</label>\n"
"          <input type=\"text\" id=\"autologout\" name=\"autologout\" value=\"5\">\n"
"        </div>\n"
"        <h3>Temperature Unit</h3>\n"
"        <hr color=\"#333333\">\n"
"        <div class=\"form-group\">\n"
"          <input type=\"radio\" id=\"celsius\" name=\"temp_unit\" value=\"celsius\" checked>\n"
"          <label for=\"celsius\">Celsius</label>\n"
"        </div>\n"
"        <div class=\"form-group\">\n"
"          <input type=\"radio\" id=\"fahrenheit\" name=\"temp_unit\" value=\"fahrenheit\">\n"
"          <label for=\"fahrenheit\">Fahrenheit</label>\n"
"        </div>\n"
"        <div class=\"form-group\">\n"
"          <input type=\"radio\" id=\"kelvin\" name=\"temp_unit\" value=\"kelvin\">\n"
"          <label for=\"kelvin\">Kelvin</label>\n"
"        </div>\n"
"        <br>\n"
"        <input type=\"submit\" value=\"Save Settings\" class=\"btn\">\n"
"      </form>\n"
"      <h3>Manuals</h3>\n"
"      <hr color=\"#333333\">\n"
"      <p>\n"
"        <a href=\"user_manual.html\">User Manual</a><br>\n"
"        <a href=\"programming_manual.html\">Programming &amp; Interfacing Manual</a>\n"
"      </p>\n"
"    </div>\n"
"  </div>\n"
"</body>\n"
"</html>\n";

#endif // HTML_SETTINGS_H
